
# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Local dev server settings for Vite (port 8080)
[dev]
  command = "vite"
  targetPort = 8080
  port = 8888

# Enable pre-rendering for better SEO and social media sharing
[[plugins]]
  package = "@netlify/plugin-prerender-spa"
  
  [plugins.inputs]
    # Prerender these specific routes and patterns
    routes = [
      "/",
      "/about",
      "/services", 
      "/portfolio",
      "/blog",
      "/blog/*",
      "/contact",
      "/solutions",
      "/privacy-policy",
      "/terms-of-service"
    ]
    # Enhanced crawler detection for better social media sharing
    crawlerUserAgents = [
      "facebookexternalhit",
      "facebookexternalhit/1.1",
      "Facebot",
      "linkedinbot", 
      "LinkedInBot/1.0",
      "twitterbot",
      "Twitterbot/1.0",
      "googlebot",
      "Googlebot/2.1",
      "bingbot",
      "BingBot/2.0",
      "slackbot",
      "Slackbot-LinkExpanding",
      "whatsapp",
      "WhatsApp/2.0",
      "TelegramBot",
      "SkypeUriPreview",
      "discordbot",
      "RedditBot",
      "applebot"
    ]
    # Force pre-rendering for all crawlers
    ignoreHTMLErrors = false
    # Set a longer timeout for complex pages
    renderAfterTime = 2000

# Headers for static files
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    Cache-Control = "public, max-age=86400"

# Enhanced headers for better social media sharing
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Blog post redirects
[[redirects]]
  from = "/blog/10-free-ai-marketing-tools-2025"
  to = "/blog/free-ai-tools-marketing-2025"
  status = 301

# Static file redirects với priority cao nhất
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true
  headers = {Content-Type = "application/xml"}

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true
  headers = {Content-Type = "text/plain"}

[[redirects]]
  from = "/site.webmanifest"
  to = "/site.webmanifest"
  status = 200
  force = true

# SPA fallback cho tất cả các route khác (priority thấp nhất)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
