
# Build settings
[build]
  publish = "dist"

# Local dev server settings for Vite (port 8080)
[dev]
  command = "vite"
  targetPort = 8080
  port = 8888

# Headers for static files - sitemap.xml phải có Content-Type chính xác
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Cache-Control = "public, max-age=3600"
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    Cache-Control = "public, max-age=86400"

# Static file redirects với priority cao nhất - quan trọng để tránh conflict
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true
  headers = {Content-Type = "application/xml"}

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true
  headers = {Content-Type = "text/plain"}

[[redirects]]
  from = "/site.webmanifest"
  to = "/site.webmanifest"
  status = 200
  force = true

# SPA fallback cho tất cả các route khác (priority thấp nhất)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Plugin Visual Editor
[[plugins]]
  package = "@netlify/plugin-visual-editor"
