
# Build settings
[build]
  publish = "dist"

# Local dev server settings for Vite (port 8080)
[dev]
  command = "vite"
  targetPort = 8080
  port = 8888

# Headers for static files
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    Cache-Control = "public, max-age=86400"

# Allow search engines to index all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

# Blog post redirects
[[redirects]]
  from = "/blog/10-free-ai-marketing-tools-2025"
  to = "/blog/free-ai-tools-marketing-2025"
  status = 301

# Static file redirects với priority cao nhất
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true
  headers = {Content-Type = "application/xml"}

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true
  headers = {Content-Type = "text/plain"}

[[redirects]]
  from = "/site.webmanifest"
  to = "/site.webmanifest"
  status = 200
  force = true

# Serve static HTML to social media crawlers
[[redirects]]
  from = "/"
  to = "/index-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/about"
  to = "/about-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/blog"
  to = "/blog-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

# Blog post static pages for crawlers
[[redirects]]
  from = "/blog/free-ai-tools-marketing-2025"
  to = "/blog-free-ai-tools-marketing-2025-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/blog/create-infographics-with-canva-free"
  to = "/blog-create-infographics-with-canva-free-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/blog/linkedin-personal-branding-mistakes-marketing-services"
  to = "/blog-linkedin-personal-branding-mistakes-marketing-services-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

# SPA fallback cho tất cả các route khác (priority thấp nhất)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Plugin Visual Editor
[[plugins]]
  package = "@netlify/plugin-visual-editor"
