[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "max-age=0"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
