
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "max-age=0"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

# Fallback for SPA - but exclude static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}
  force = false

# Serve static files directly (this should come after SPA fallback)
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true
