
# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Local dev server settings for Vite (port 8080)
[dev]
  command = "vite"
  targetPort = 8080
  port = 8888

# Enhanced headers for better social media sharing
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Cache static assets
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    Cache-Control = "public, max-age=86400"

# Blog post redirects
[[redirects]]
  from = "/blog/10-free-ai-marketing-tools-2025"
  to = "/blog/free-ai-tools-marketing-2025"
  status = 301

# Static file redirects với priority cao nhất
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true
  headers = {Content-Type = "application/xml"}

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true
  headers = {Content-Type = "text/plain"}

[[redirects]]
  from = "/site.webmanifest"
  to = "/site.webmanifest"
  status = 200
  force = true

# Crawler detection and static blog page serving
[[redirects]]
  from = "/blog/free-ai-tools-marketing-2025"
  to = "/blog/free-ai-tools-marketing-2025.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit*", "linkedinbot*", "twitterbot*", "googlebot*", "bingbot*", "slackbot*", "whatsapp*", "telegrambot*", "skypeuripreview*", "discordbot*", "redditbot*", "applebot*"]}

[[redirects]]
  from = "/blog/linkedin-personal-branding-mistakes-marketing-services"
  to = "/blog/linkedin-personal-branding-mistakes-marketing-services.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit*", "linkedinbot*", "twitterbot*", "googlebot*", "bingbot*", "slackbot*", "whatsapp*", "telegrambot*", "skypeuripreview*", "discordbot*", "redditbot*", "applebot*"]}

[[redirects]]
  from = "/blog/create-infographics-with-canva-free"
  to = "/blog/create-infographics-with-canva-free.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit*", "linkedinbot*", "twitterbot*", "googlebot*", "bingbot*", "slackbot*", "whatsapp*", "telegrambot*", "skypeuripreview*", "discordbot*", "redditbot*", "applebot*"]}

# SPA fallback cho tất cả các route khác (priority thấp nhất)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
