
# Build settings
[build]
  publish = "dist"

# Local dev server settings for Vite (port 8080)
[dev]
  command = "vite"
  targetPort = 8080
  port = 8888

# Headers for static files
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    Cache-Control = "public, max-age=86400"

# Allow search engines to index all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

# 410 Gone responses for permanently deleted pages
[[redirects]]
  from = "/solutions/tools/seo-assistant"
  to = "/410"
  status = 410

[[redirects]]
  from = "/solutions/free-resources/local-seo-checklist"
  to = "/410"
  status = 410

[[redirects]]
  from = "/blog/marketing-trends-2025"
  to = "/410"
  status = 410

[[redirects]]
  from = "/blog/ai-marketing-complete-guide"
  to = "/410"
  status = 410

[[redirects]]
  from = "/services/ai-marketing"
  to = "/410"
  status = 410

# Redirect main solutions page to free resources
[[redirects]]
  from = "/solutions"
  to = "/solutions/free-resources"
  status = 301

# Blog post redirects
[[redirects]]
  from = "/blog/10-free-ai-marketing-tools-2025"
  to = "/blog/free-ai-tools-marketing-2025"
  status = 301

# Serve static HTML to social media crawlers
[[redirects]]
  from = "/"
  to = "/index-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/about"
  to = "/about-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/services"
  to = "/services-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/portfolio"
  to = "/portfolio-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/contact"
  to = "/contact-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/blog"
  to = "/blog-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

# Blog post static pages for crawlers
[[redirects]]
  from = "/blog/free-ai-tools-marketing-2025"
  to = "/blog-free-ai-tools-marketing-2025-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/blog/create-infographics-with-canva-free"
  to = "/blog-create-infographics-with-canva-free-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/blog/linkedin-personal-branding-mistakes-marketing-services"
  to = "/blog-linkedin-personal-branding-mistakes-marketing-services-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

# Solutions sub-pages static pages for crawlers
[[redirects]]
  from = "/solutions/free-resources"
  to = "/solutions-free-resources-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/solutions/ai-tools"
  to = "/solutions-ai-tools-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/solutions/marketing-tools-hub"
  to = "/solutions-marketing-tools-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/solutions/ai-tools/marketing-budget-planner"
  to = "/ai-tools-marketing-budget-planner-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/solutions/free-resources/roi-calculator"
  to = "/free-resources-roi-calculator-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/solutions/free-resources/on-page-seo-checklist"
  to = "/free-resources-on-page-seo-checklist-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/solutions/free-resources/seo-optimization-checklist"
  to = "/free-resources-seo-optimization-checklist-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/solutions/free-resources/social-media-growth-tools"
  to = "/free-resources-social-media-growth-tools-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/solutions/free-resources/marketing-with-canva"
  to = "/free-resources-marketing-with-canva-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

# Portfolio sub-pages static pages for crawlers
[[redirects]]
  from = "/portfolio/fmcg-dao-strategy"
  to = "/portfolio-fmcg-dao-strategy-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/portfolio/microlino-strategy"
  to = "/portfolio-microlino-strategy-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/portfolio/i-choose-the-sun"
  to = "/portfolio-i-choose-the-sun-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/portfolio/nha-ca-cafe"
  to = "/portfolio-nha-ca-cafe-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/portfolio/koto-club"
  to = "/portfolio-koto-club-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

[[redirects]]
  from = "/portfolio/lua-hong-buffet"
  to = "/portfolio-lua-hong-buffet-static.html"
  status = 200
  conditions = {User-Agent = ["facebookexternalhit", "twitterbot", "linkedinbot", "slurp", "whatsapp", "*bot*", "*crawler*", "*spider*"]}

# SPA fallback cho tất cả các route khác (priority thấp nhất)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Plugin Visual Editor
[[plugins]]
  package = "@netlify/plugin-visual-editor"
