// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yroritnzsvmxuiabipxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyb3JpdG56c3ZteHVpYWJpcHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTMxMjIsImV4cCI6MjA2NjU2OTEyMn0.i7F-LOMn4TDHwwD8f6vrneWfYz7fpexuLxlNjOu3-6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});